-- 코드를 입력하세요
SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    I.GENDER AS GENDER, 
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO I
RIGHT JOIN ONLINE_SALE O ON I.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 
    YEAR(O.SALES_DATE), 
    MONTH(O.SALES_DATE), 
    I.GENDER
ORDER BY 
    YEAR ASC,
    MONTH ASC,
    GENDER ASC;