SELECT CAR_ID,
       CASE
           WHEN MAX(START_DATE) <= '2022-10-16' AND MAX(END_DATE) >= '2022-10-16' THEN '대여중'
           ELSE '대여 가능'
       END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' -- 대여가 시작된 자동차들만 선택
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

