-- 코드를 작성해주세요
SELECT 
    SUM(CASE
        WHEN G.HALF_YEAR = 1 THEN G.SCORE
        ELSE 0
        END)
    +SUM(CASE
        WHEN G.HALF_YEAR = 2 THEN G.SCORE
        ELSE 0
        END)
        AS SCORE, 
    E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
    limit 1;

